spring:
  application:
    name: discodeit

discodeit:
  repository:
    type: file   # jcf | file
    file-directory: .discodeit
logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG