spring:
  application:
    name: discodeit

server:
  port: ${PORT:8080}

discodeit:
  repository:
    type: file
    file-directory: .discodeit

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG